(in-package #:avro-protocol)

;;; Minimal JSON reader for Avro schemas. Same scalars as json-protocol.

(defun %skip-ws (string i)
  (loop for n from i below (length string)
        for c = (char string n)
        while (or (char= c #\Space) (char= c #\Tab)
                  (char= c #\Newline) (char= c #\Return))
        finally (return n)))

(defun %parse-string (string i)
  (unless (char= (char string i) #\")
    (error 'avro-schema-error :message "expected JSON string"))
  (let ((out (make-string-output-stream))
        (n (1+ i)))
    (loop
      (when (>= n (length string))
        (error 'avro-schema-error :message "unterminated JSON string"))
      (let ((c (char string n)))
        (cond
          ((char= c #\")
           (return (values (get-output-stream-string out) (1+ n))))
          ((char= c #\\)
           (incf n)
           (when (>= n (length string))
             (error 'avro-schema-error :message "truncated JSON escape"))
           (let ((e (char string n)))
             (write-char (case e
                           (#\" #\")
                           (#\\ #\\)
                           (#\/ #\/)
                           (#\b #\Backspace)
                           (#\f #\Page)
                           (#\n #\Newline)
                           (#\r #\Return)
                           (#\t #\Tab)
                           (#\u
                            (when (> (+ n 5) (length string))
                              (error 'avro-schema-error :message "truncated \\u"))
                            (let ((code (parse-integer string :start (1+ n) :end (+ n 5) :radix 16)))
                              (incf n 4)
                              (code-char code)))
                           (t e))
                         out)
             (incf n)))
          (t
           (write-char c out)
           (incf n)))))))

(defun %parse-number (string i)
  (let ((end i)
        (n (length string)))
    (when (and (< end n) (char= (char string end) #\-))
      (incf end))
    (loop while (and (< end n) (digit-char-p (char string end)))
          do (incf end))
    (when (and (< end n) (char= (char string end) #\.))
      (incf end)
      (loop while (and (< end n) (digit-char-p (char string end)))
            do (incf end)))
    (when (and (< end n) (find (char string end) "eE" :test #'char=))
      (incf end)
      (when (and (< end n) (find (char string end) "+-" :test #'char=))
        (incf end))
      (loop while (and (< end n) (digit-char-p (char string end)))
            do (incf end)))
    (let* ((token (subseq string i end))
           (num (if (find-if (lambda (c) (find c ".eE" :test #'char=)) token)
                    (let ((*read-default-float-format* 'double-float))
                      (read-from-string token))
                    (parse-integer token))))
      (values num end))))

(defun parse-json (string &optional (i 0))
  (setf i (%skip-ws string i))
  (when (>= i (length string))
    (error 'avro-schema-error :message "empty JSON"))
  (let ((c (char string i)))
    (cond
      ((char= c #\")
       (%parse-string string i))
      ((or (char= c #\-) (digit-char-p c))
       (%parse-number string i))
      ((and (<= (+ i 4) (length string)) (string= string "true" :start1 i :end1 (+ i 4)))
       (values t (+ i 4)))
      ((and (<= (+ i 5) (length string)) (string= string "false" :start1 i :end1 (+ i 5)))
       (values nil (+ i 5)))
      ((and (<= (+ i 4) (length string)) (string= string "null" :start1 i :end1 (+ i 4)))
       (values :null (+ i 4)))
      ((char= c #\[)
       (let ((acc '())
             (n (%skip-ws string (1+ i))))
         (when (and (< n (length string)) (char= (char string n) #\]))
           (return-from parse-json (values #() (1+ n))))
         (loop
           (multiple-value-bind (v next) (parse-json string n)
             (push v acc)
             (setf n (%skip-ws string next))
             (cond
               ((and (< n (length string)) (char= (char string n) #\,))
                (setf n (%skip-ws string (1+ n))))
               ((and (< n (length string)) (char= (char string n) #\]))
                (return (values (coerce (nreverse acc) 'vector) (1+ n))))
               (t (error 'avro-schema-error :message "expected ',' or ']' in JSON array")))))))
      ((char= c #\{)
       (let ((ht (make-hash-table :test #'equal))
             (n (%skip-ws string (1+ i))))
         (when (and (< n (length string)) (char= (char string n) #\}))
           (return-from parse-json (values ht (1+ n))))
         (loop
           (multiple-value-bind (k next) (parse-json string n)
             (unless (stringp k)
               (error 'avro-schema-error :message "JSON object key must be a string"))
             (setf n (%skip-ws string next))
             (unless (and (< n (length string)) (char= (char string n) #\:))
               (error 'avro-schema-error :message "expected ':' in JSON object"))
             (multiple-value-bind (v next2) (parse-json string (1+ n))
               (setf (gethash k ht) v
                     n (%skip-ws string next2))
               (cond
                 ((and (< n (length string)) (char= (char string n) #\,))
                  (setf n (%skip-ws string (1+ n))))
                 ((and (< n (length string)) (char= (char string n) #\}))
                  (return (values ht (1+ n))))
                 (t (error 'avro-schema-error :message "expected ',' or '}' in JSON object"))))))))
      (t
       (error 'avro-schema-error :message (format nil "unexpected JSON at ~D" i))))))
